/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package s.docker.com.jcurl;

public class CurlUtilsJNI {
  public final static native long CurlUtil_getInstance();
  public final static native String CurlUtil_get(long jarg1, CurlUtil jarg1_, String jarg2);
}
