/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package s.docker.com.jcurl;

public class CurlUtilsJNI {
  public final static native long CurlUtil_getInstance();
  public final static native String CurlUtil_get(long jarg1, CurlUtil jarg1_, String jarg2, long jarg3, Response jarg3_);
  public final static native void Response_callback(long jarg1, Response jarg1_, int jarg2, String jarg3);
  public final static native long new_Response();
  public final static native void delete_Response(long jarg1);
  public final static native void curlUtil_set(long jarg1, CurlUtil jarg1_);
  public final static native long curlUtil_get();
}
