/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package s.docker.com.jcurl;

public class CurlUtilsJNI {
  public final static native void Response_callback(long jarg1, Response jarg1_, int jarg2, String jarg3);
  public final static native void Response_callbackSwigExplicitResponse(long jarg1, Response jarg1_, int jarg2, String jarg3);
  public final static native long new_Response();
  public final static native void delete_Response(long jarg1);
  public final static native void Response_director_connect(Response obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void Response_change_ownership(Response obj, long cptr, boolean take_or_release);
  public final static native void ByteResponse_callback(long jarg1, ByteResponse jarg1_, int jarg2, java.nio.ByteBuffer jarg3, long jarg4);
  public final static native void ByteResponse_callbackSwigExplicitByteResponse(long jarg1, ByteResponse jarg1_, int jarg2, java.nio.ByteBuffer jarg3, long jarg4);
  public final static native long new_ByteResponse();
  public final static native void delete_ByteResponse(long jarg1);
  public final static native void ByteResponse_director_connect(ByteResponse obj, long cptr, boolean mem_own, boolean weak_global);
  public final static native void ByteResponse_change_ownership(ByteResponse obj, long cptr, boolean take_or_release);
  public final static native long CurlUtil_getInstance();
  public final static native long CurlUtil_get(long jarg1, CurlUtil jarg1_, String jarg2, long jarg3, Response jarg3_);
  public final static native long CurlUtil_getBytes(long jarg1, CurlUtil jarg1_, String jarg2, long jarg3, ByteResponse jarg3_);
  public final static native void curlUtil_set(long jarg1, CurlUtil jarg1_);
  public final static native long curlUtil_get();

  public static void SwigDirector_Response_callback(Response jself, int result, String s) {
    jself.callback(result, s);
  }
  public static void SwigDirector_ByteResponse_callback(ByteResponse jself, int result, java.nio.ByteBuffer buf, long len) {
    jself.callback(result, buf, len);
  }

  private final static native void swig_module_init();
  static {
    swig_module_init();
  }
}
