/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package s.docker.com.jcurl;

public class CurlUtil {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected CurlUtil(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(CurlUtil obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        throw new UnsupportedOperationException("C++ destructor does not have public access");
      }
      swigCPtr = 0;
    }
  }

  public static CurlUtil getInstance() {
    long cPtr = CurlUtilsJNI.CurlUtil_getInstance();
    return (cPtr == 0) ? null : new CurlUtil(cPtr, false);
  }

  public CurlUtil get(String url, Response response) {
    long cPtr = CurlUtilsJNI.CurlUtil_get__SWIG_0(swigCPtr, this, url, Response.getCPtr(response), response);
    return (cPtr == 0) ? null : new CurlUtil(cPtr, false);
  }

  public CurlUtil get(String url, SWIGTYPE_p_std__functionT_void_fint_std__stringF_t arg1) {
    long cPtr = CurlUtilsJNI.CurlUtil_get__SWIG_1(swigCPtr, this, url, SWIGTYPE_p_std__functionT_void_fint_std__stringF_t.getCPtr(arg1));
    return (cPtr == 0) ? null : new CurlUtil(cPtr, false);
  }

  public CurlUtil getBytes(String url, ByteResponse response) {
    long cPtr = CurlUtilsJNI.CurlUtil_getBytes(swigCPtr, this, url, ByteResponse.getCPtr(response), response);
    return (cPtr == 0) ? null : new CurlUtil(cPtr, false);
  }

}
