/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package s.docker.com.jcurl;

public class Map {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected Map(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(Map obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CurlUtilsJNI.delete_Map(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Map() {
    this(CurlUtilsJNI.new_Map__SWIG_0(), true);
  }

  public Map(Map arg0) {
    this(CurlUtilsJNI.new_Map__SWIG_1(Map.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return CurlUtilsJNI.Map_size(swigCPtr, this);
  }

  public boolean empty() {
    return CurlUtilsJNI.Map_empty(swigCPtr, this);
  }

  public void clear() {
    CurlUtilsJNI.Map_clear(swigCPtr, this);
  }

  public String get(String key) {
    return CurlUtilsJNI.Map_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    CurlUtilsJNI.Map_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    CurlUtilsJNI.Map_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return CurlUtilsJNI.Map_has_key(swigCPtr, this, key);
  }

}
