/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.my.jcurl;

public class ParamArray {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ParamArray(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParamArray obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CurlUtilsJNI.delete_ParamArray(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParamArray() {
    this(CurlUtilsJNI.new_ParamArray__SWIG_0(), true);
  }

  public ParamArray(long n) {
    this(CurlUtilsJNI.new_ParamArray__SWIG_1(n), true);
  }

  public long size() {
    return CurlUtilsJNI.ParamArray_size(swigCPtr, this);
  }

  public long capacity() {
    return CurlUtilsJNI.ParamArray_capacity(swigCPtr, this);
  }

  public void reserve(long n) {
    CurlUtilsJNI.ParamArray_reserve(swigCPtr, this, n);
  }

  public boolean isEmpty() {
    return CurlUtilsJNI.ParamArray_isEmpty(swigCPtr, this);
  }

  public void clear() {
    CurlUtilsJNI.ParamArray_clear(swigCPtr, this);
  }

  public void add(String x) {
    CurlUtilsJNI.ParamArray_add(swigCPtr, this, x);
  }

  public String get(int i) {
    return CurlUtilsJNI.ParamArray_get(swigCPtr, this, i);
  }

  public void set(int i, String val) {
    CurlUtilsJNI.ParamArray_set(swigCPtr, this, i, val);
  }

}
