/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.my.jcurl;

public class ParamFormMap {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  protected ParamFormMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParamFormMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CurlUtilsJNI.delete_ParamFormMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParamFormMap() {
    this(CurlUtilsJNI.new_ParamFormMap__SWIG_0(), true);
  }

  public ParamFormMap(ParamFormMap arg0) {
    this(CurlUtilsJNI.new_ParamFormMap__SWIG_1(ParamFormMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return CurlUtilsJNI.ParamFormMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return CurlUtilsJNI.ParamFormMap_empty(swigCPtr, this);
  }

  public void clear() {
    CurlUtilsJNI.ParamFormMap_clear(swigCPtr, this);
  }

  public ParamFormData get(String key) {
    long cPtr = CurlUtilsJNI.ParamFormMap_get(swigCPtr, this, key);
    return (cPtr == 0) ? null : new ParamFormData(cPtr, false);
  }

  public void set(String key, ParamFormData x) {
    CurlUtilsJNI.ParamFormMap_set(swigCPtr, this, key, ParamFormData.getCPtr(x), x);
  }

  public void del(String key) {
    CurlUtilsJNI.ParamFormMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return CurlUtilsJNI.ParamFormMap_has_key(swigCPtr, this, key);
  }

}
