/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 3.0.12
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package com.my.jcurl;

public class ParamMap {
  private transient long swigCPtr;
  protected transient boolean swigCMemOwn;

  protected ParamMap(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  protected static long getCPtr(ParamMap obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CurlUtilsJNI.delete_ParamMap(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public ParamMap() {
    this(CurlUtilsJNI.new_ParamMap__SWIG_0(), true);
  }

  public ParamMap(ParamMap arg0) {
    this(CurlUtilsJNI.new_ParamMap__SWIG_1(ParamMap.getCPtr(arg0), arg0), true);
  }

  public long size() {
    return CurlUtilsJNI.ParamMap_size(swigCPtr, this);
  }

  public boolean empty() {
    return CurlUtilsJNI.ParamMap_empty(swigCPtr, this);
  }

  public void clear() {
    CurlUtilsJNI.ParamMap_clear(swigCPtr, this);
  }

  public String get(String key) {
    return CurlUtilsJNI.ParamMap_get(swigCPtr, this, key);
  }

  public void set(String key, String x) {
    CurlUtilsJNI.ParamMap_set(swigCPtr, this, key, x);
  }

  public void del(String key) {
    CurlUtilsJNI.ParamMap_del(swigCPtr, this, key);
  }

  public boolean has_key(String key) {
    return CurlUtilsJNI.ParamMap_has_key(swigCPtr, this, key);
  }

}
